<?php
/**
 * @file
 * Base module file for package
 *
 * @defgroup package Package
 * @{
 */

/**
 * @return mixed
 * @deprecated Use \Drupal::service('web_package')->getInfoFilepath() instead.
 */
function web_package_filepath() {
  return \Drupal::service('web_package')->getInfoFilepath();
}

/**
 * @return mixed
 * @deprecated Use \Drupal::service('web_package')->getInfo() instead.
 */
function web_package_info() {
  return \Drupal::service('web_package')->getInfo();

}

/**
 * @return mixed
 * @deprecated Use \Drupal::service('web_package')->getVersion() instead.
 */
function web_package_get_version() {
  return \Drupal::service('web_package')->getVersion();
}

/**
 * @return mixed
 * @deprecated use \Drupal::service('web_package')->createCacheBusterUrl()
 *   instead.
 */
function web_package_cache_buster_url() {
  return \Drupal::service('web_package')
    ->createCacheBusterUrl($path = NULL, $options = [], $key = 'vs');
}

function web_package_admin_menu_output_build(&$content) {
  if (($info = \Drupal::service('web_package')->getInfo())
    && isset($info['version'])) {
    $content['menu']['web_package'] = [
      '#title' => t('v@version', ['@version' => $info['version']]),
      '#weight' => 0,
      '#href' => 'admin/reports/status',
      '#attributes' => [
        //admin-menu-action: floats it right
        'class' => [
          'admin-menu-action',
          'admin-menu-menu',
          'web-package-version',
        ],
      ],
    ];
  }
}

/**
 * Implements hook_loft_deploy_title_pre_alter().
 */
function web_package_loft_deploy_title_pre_alter(&$title) {
  try {
    if (($info = \Drupal::service('web_package')->getInfo())
      && isset($info['version'])) {
      $title .= t(' ~ Ver: @version', ['@version' => $info['version']]);
    }
  }
  catch (\Exception $exception) {
    watchdog_exception('web_package', $exception);
  }
}
