<?php
/**
 * @file
 * Base module file for package
 *
 * @defgroup package Package
 * @{
 */

use Drupal\Core\Url;

/**
 * Implements hook_toolbar_alter().
 *
 * Add the version to the Toolbar.
 */
function web_package_toolbar_alter(&$items) {
  $lowest_weight = 0;
  foreach ($items as $item) {
    $weight = isset($item['#weight']) ? $item['#weight'] : 0;
    $lowest_weight = min($lowest_weight, $weight);
  }
  $items['web_package'] = [
    '#type' => 'toolbar_item',
    '#weight' => $lowest_weight - 1,
    '#wrapper_attributes' => [
      'class' => ['contextual-toolbar-tab'],
    ],
    'tab' => [
      '#type' => 'link',
      '#title' => \Drupal::service('web_package')->getVersion(),
      '#url' => Url::fromRoute('system.status'),
    ],
  ];
}

/**
 * Implements hook_loft_deploy_title_pre_alter().
 *
 * Add the version to the title.
 */
function web_package_loft_deploy_title_pre_alter(&$title) {
  try {
    if (($info = \Drupal::service('web_package')->getInfo())
      && isset($info['version'])) {
      $title .= t(' ~ Ver: @version', ['@version' => $info['version']]);
    }
  }
  catch (\Exception $exception) {
    watchdog_exception('web_package', $exception);
  }
}
